kind: pipeline
type: docker
name: default 
steps: 
  - name: flake8
    image: python:3.7    
    commands:
       - python test.py    
    when:      
      event:      
        - push      
        - pull_request
