kind: pipeline
type: docker
name: default 
steps: 
  - name: flake8
    image: python:3.7    
    commands:
      - echo 'print("123")' > my_script.py  # 创建一个Python脚本文件
      - python my_script.py  # 运行Python脚本文件    
    when:      
      event:      
        - push      
        - pull_request
